environment:
  matrix:
    - platform: x64

image: Visual Studio 2019

install:
  - ps: Install-Product node 13 x64
  - npm install
  - npm install -g gitbook-cli
  - cd docs && gitbook install && cd ../ && npm run build-docs-pdf

# Don't actually build.
build: off